// Auto-generated from kaikki.org-dictionary-all.jsonl
export const LANG_LABELS: Record<string, string> = {
    'aa': 'Tiếng Afar',
    'aaa': 'Tiếng Ghotuo',
    'aab': 'Tiếng Alumu-Tesu',
    'aac': 'Tiếng Ari',
    'aad': 'Tiếng Amal',
    'aaf': 'Tiếng Aranadan',
    'aag': 'Tiếng Ambrak',
    'aak': 'Tiếng Ankave',
    'aaq': 'Tiếng Đông Abenaki',
    'aas': 'Tiếng Aasax',
    'aau': 'Tiếng Abau',
    'aav-bhu': 'Tiếng Bhumij',
    'aav-tam': 'Tiếng Tà Mun',
    'aaw': 'Tiếng Solong',
    'aaz': 'Tiếng Amarasi',
    'ab': 'Tiếng Abkhaz',
    'abb': 'Tiếng Bankon',
    'abe': 'Tiếng Tây Abenaki',
    'abg': 'Tiếng Abaga',
    'abh': 'Tiếng Ả Rập Tajikistan',
    'abi': 'Tiếng Abidji',
    'abm': 'Tiếng Abanyom',
    'abo': 'Tiếng Abon',
    'abq': 'Tiếng Abaza',
    'abr': 'Tiếng Abron',
    'abs': 'Tiếng Mã Lai Ambon',
    'abt': 'Tiếng Ambulas',
    'abu': 'Tiếng Abure',
    'aca': 'Tiếng Achawa',
    'ace': 'Tiếng Aceh',
    'acm': 'Tiếng Ả Rập Iraq',
    'acn': 'Tiếng A Xương',
    'acr': 'Tiếng Achi',
    'acu': 'Tiếng Achuar',
    'acw': 'Tiếng Ả Rập Hijazi',
    'acy': 'Tiếng Ả Rập Síp',
    'acz': 'Tiếng Acheron',
    'ada': 'Tiếng Adangme',
    'adx': 'Tiếng Tây Tạng Amdo',
    'ady': 'Tiếng Adygea',
    'adz': 'Tiếng Adzera',
    'ae': 'Tiếng Avesta',
    'aem': 'Tiếng Arem',
    'aes': 'Tiếng Alsea',
    'af': 'Tiếng Afrikaans',
    'afb': 'Tiếng Ả Rập vùng Vịnh',
    'agc': 'Tiếng Agatu',
    'agj': 'Tiếng Argobba',
    'agq': 'Tiếng Aghem',
    'ags': 'Tiếng Esimbi',
    'agx': 'Tiếng Aghul',
    'ahk': 'Tiếng Akha',
    'aho': 'Tiếng Ahom',
    'aht': 'Tiếng Ahtna',
    'aib': 'Tiếng Äynu',
    'aii': 'Tiếng Tân Aram Assyria',
    'aim': 'Tiếng Aimol',
    'ain': 'Tiếng Ainu',
    'aio': 'Tiếng Aiton',
    'aiw': 'Tiếng Aari',
    'ajg': 'Tiếng Adja',
    'ajp': 'Tiếng Ả Rập Nam Levant',
    'ak': 'Tiếng Akan',
    'ake': 'Tiếng Akawaio',
    'akj': 'Tiếng Aka-Jeru',
    'akk': 'Tiếng Akkad',
    'akl': 'Tiếng Aklanon',
    'akp': 'Tiếng Siwu',
    'akr': 'Tiếng Araki',
    'akv': 'Tiếng Akhvakh',
    'akz': 'Tiếng Alabama',
    'alc': 'Tiếng Kawésqar',
    'ale': 'Tiếng Aleut',
    'alg-aga': 'Tiếng Agawam',
    'alh': 'Tiếng Alawa',
    'ali': 'Tiếng Amaimon',
    'alj': 'Tiếng Alangan',
    'alk': 'Tiếng Alak',
    'all': 'Tiếng Allar',
    'alq': 'Tiếng Algonquin',
    'alr': 'Tiếng Alutor',
    'alt': 'Tiếng Nam Altai',
    'alu': 'Tiếng \'Are\'are',
    'alw': 'Tiếng Alaba-K’abeena',
    'am': 'Tiếng Amhara',
    'amc': 'Tiếng Amahuaca',
    'amf': 'Tiếng Hamer-Banna',
    'ami': 'Tiếng Amis',
    'amk': 'Tiếng Ambai',
    'aml': 'Tiếng War-Jaintia',
    'amm': 'Tiếng Ama',
    'amp': 'Tiếng Alamblak',
    'ams': 'Tiếng Nam Amami Ōshima',
    'an': 'Tiếng Aragon',
    'anc': 'Tiếng Ngas',
    'ane': 'Tiếng Xârâcùù',
    'ang': 'Tiếng Anh cổ',
    'ani': 'Tiếng Andi',
    'anm': 'Tiếng Anal',
    'anp': 'Tiếng Angika',
    'anq': 'Tiếng Jarawa',
    'any': 'Tiếng Anyi',
    'aot': 'Tiếng Atong (Ấn Độ)',
    'aou': 'Tiếng A\'ou',
    'apc': 'Tiếng Ả Rập Bắc Levant',
    'apd': 'Tiếng Ả Rập Sudan',
    'aph': 'Tiếng Athpariya',
    'apx': 'Tiếng Aputai',
    'apy': 'Tiếng Aparaí',
    'aqc': 'Tiếng Archi',
    'aqz': 'Tiếng Akuntsu',
    'ar': 'Tiếng Ả Rập',
    'arc': 'Tiếng Aram',
    'arh': 'Tiếng Arhuaco',
    'arn': 'Tiếng Mapuche',
    'arw': 'Tiếng Lokono',
    'ary': 'Tiếng Ả Rập Maroc',
    'arz': 'Tiếng Ả Rập Ai Cập',
    'as': 'Tiếng Assam',
    'asb': 'Tiếng Assiniboine',
    'ask': 'Tiếng Ashkun',
    'asr': 'Tiếng Asur',
    'ast': 'Tiếng Asturias',
    'atb': 'Tiếng Zaiwa',
    'atc': 'Tiếng Atsahuaca',
    'atj': 'Tiếng Atikamekw',
    'atv': 'Tiếng Bắc Altai',
    'aua': 'Tiếng Asumboa',
    'aui': 'Tiếng Anuki',
    'aus-ang': 'Tiếng Angkula',
    'auz': 'Tiếng Ả Rập Uzbekistan',
    'av': 'Tiếng Avar',
    'avu': 'Tiếng Avokaya',
    'awa': 'Tiếng Awadh',
    'awd-ana': 'Tiếng Anauyá',
    'awd-she': 'Tiếng Shebayo',
    'awn': 'Tiếng Awngi',
    'awx': 'unknown',
    'ay': 'Tiếng Aymara',
    'aye': 'Tiếng Ayere',
    'ayl': 'Tiếng Ả Rập Libya',
    'az': 'Tiếng Azerbaijan',
    'azo': 'Tiếng Awing',
    'ba': 'Tiếng Bashkir',
    'bal': 'Tiếng Baloch',
    'ban': 'Tiếng Bali',
    'bap': 'Tiếng Bantawa',
    'bar': 'Tiếng Bayern',
    'bas': 'Tiếng Basaa',
    'bax': 'Tiếng Bamum',
    'bay': 'Tiếng Batuley',
    'bbb': 'Tiếng Barai',
    'bbh': 'Tiếng Bố Cam',
    'bbi': 'Tiếng Barombi',
    'bbj': 'Tiếng Ghomala\'',
    'bbl': 'Tiếng Bats',
    'bca': 'Tiếng Bạch Trung',
    'bci': 'Tiếng Baoule',
    'bcl': 'Tiếng Trung Bikol',
    'bcq': 'Tiếng Bench',
    'bdk': 'Tiếng Budukh',
    'bdq': 'Tiếng Ba Na',
    'bds': 'Tiếng Burunge',
    'bdv': 'Tiếng Bodo Parja',
    'be': 'Tiếng Belarus',
    'bej': 'Tiếng Beja',
    'bem': 'Tiếng Bemba',
    'ber-fog': 'Tiếng Fogaha',
    'beu': 'Tiếng Blagar',
    'bfa': 'Tiếng Bari',
    'bfq': 'Tiếng Badaga',
    'bfs': 'Tiếng Bạch Nam',
    'bft': 'Tiếng Balti',
    'bfu': 'Tiếng Gahri',
    'bfw': 'Tiếng Bondo',
    'bg': 'Tiếng Bulgari',
    'bgj': 'Tiếng Bangolan',
    'bgk': 'Tiếng Bit',
    'bgx': 'Tiếng Thổ Nhĩ Kỳ Gagauz Balkan',
    'bgz': 'Tiếng Banggai',
    'bhb': 'Tiếng Bhil',
    'bhh': 'Tiếng Bukhara',
    'bhj': 'Tiếng Bahing',
    'bho': 'Tiếng Bhojpur',
    'bhq': 'Tiếng Tukang Besi Nam',
    'bi': 'Tiếng Bislama',
    'bib': 'Tiếng Bissa',
    'bix': 'Tiếng Birjia',
    'biy': 'Tiếng Birhor',
    'bji': 'Tiếng Burji',
    'bjj': 'Tiếng Kannauj',
    'bjn': 'Tiếng Banjar',
    'bjt': 'Tiếng Balanta-Ganja',
    'bkm': 'Tiếng Itaŋikom',
    'bku': 'Tiếng Buhid',
    'bkz': 'Tiếng Bungku',
    'bla': 'Tiếng Blackfoot',
    'blc': 'Tiếng Bella Coola',
    'ble': 'Tiếng Balanta-Kentohe',
    'blk': 'Tiếng Pa\'O',
    'blm': 'Tiếng Beli',
    'blo': 'Tiếng Anii',
    'blr': 'Tiếng Blang',
    'blt': 'Tiếng Thái Đen',
    'bm': 'Tiếng Bambara',
    'bn': 'Tiếng Bengal',
    'bnl': 'Tiếng Boon',
    'bnn': 'Tiếng Bunun',
    'bno': 'Tiếng Asi',
    'bnp': 'Tiếng Bola',
    'bo': 'Tiếng Tây Tạng',
    'boe': 'Tiếng Mundabli',
    'bph': 'Tiếng Botlikh',
    'bpy': 'Tiếng Bishnupriya',
    'bqi': 'Tiếng Bakhtiari',
    'bqp': 'Tiếng Busa',
    'bqz': 'Tiếng Bakaka',
    'br': 'Tiếng Breton',
    'bra': 'Tiếng Braj',
    'brb': 'Tiếng Brâu',
    'brh': 'Tiếng Brahui',
    'bro': 'Tiếng Brokkat',
    'bru': 'Tiếng Bru',
    'brv': 'Tiếng Bru Tây',
    'brw': 'Tiếng Bellara',
    'brx': 'Tiếng Bodo (Ấn Độ)',
    'bsa': 'Tiếng Abinomn',
    'bsc': 'Tiếng Bassari',
    'bsk': 'Tiếng Burushaski',
    'bsq': 'Tiếng Bassa',
    'bss': 'Tiếng Akoose',
    'bst': 'Tiếng Basketo',
    'bsw': 'Tiếng Baiso',
    'btn': 'Tiếng Ratagnon',
    'btq': 'Tiếng Batek',
    'bts': 'Tiếng Batak Simalungun',
    'btw': 'Tiếng Butuanon',
    'bua': 'Tiếng Buryat',
    'buc': 'Tiếng Bushi',
    'bus': 'Tiếng Bokobaru',
    'bux': 'Tiếng Boghom',
    'bvb': 'Tiếng Bube',
    'bvp': 'Tiếng Bố Mang',
    'bwe': 'Tiếng Karen Bwe',
    'bwo': 'Tiếng Shinasha',
    'bxd': 'Tiếng Pela',
    'bxe': 'Tiếng Ongota',
    'byn': 'Tiếng Bilen',
    'byq': 'Tiếng Basay',
    'byv': 'Tiếng Medumba',
    'byw': 'Tiếng Belhariya',
    'bzg': 'Tiếng Babuza',
    'bzi': 'Tiếng Bisu',
    'ca': 'Tiếng Catalan',
    'caa': 'Tiếng Ch\'orti\'',
    'cab': 'Tiếng Garifuna',
    'cae': 'Tiếng Laalaa',
    'cak': 'Tiếng Kaqchikel',
    'caq': 'Tiếng Nicobar Car',
    'car': 'Tiếng Kari\'na',
    'cay': 'Tiếng Cayuga',
    'cbi': 'Tiếng Chachi',
    'cbk': 'Tiếng Chavacano',
    'cbn': 'Tiếng Nyah Kur',
    'ccc': 'Tiếng Chamicuro',
    'ccp': 'Tiếng Chakma',
    'cda': 'Tiếng Trác Ni',
    'cdf': 'Tiếng Chiru',
    'cdh': 'Tiếng Chamba',
    'cdi': 'Tiếng Chodri',
    'cdj': 'Tiếng Churah',
    'cdm': 'Tiếng Chepang',
    'cdz': 'Tiếng Koda',
    'ce': 'Tiếng Chechen',
    'ceb': 'Tiếng Cebu',
    'cey': 'Tiếng Chin Ekai',
    'cfm': 'Tiếng Chin Falam',
    'cgk': 'Tiếng Chocangacakha',
    'ch': 'Tiếng Chamorro',
    'chb': 'Tiếng Chibcha',
    'chg': 'Tiếng Chagatai',
    'chj': 'Tiếng Chinantec Ojitlán',
    'chk': 'Tiếng Chuuk',
    'chl': 'Tiếng Cahuilla',
    'chm': 'Tiếng Mari',
    'chn': 'Biệt ngữ Chinook',
    'cho': 'Tiếng Choctaw',
    'chp': 'Tiếng Denesuline',
    'chr': 'Tiếng Cherokee',
    'chx': 'Tiếng Chantyal',
    'chy': 'Tiếng Cheyenne',
    'cia': 'Tiếng Cia-Cia',
    'cja': 'Tiếng Chăm Tây',
    'cje': 'Tiếng Chu Ru',
    'cji': 'Tiếng Chamalal',
    'cjm': 'Tiếng Chăm Đông',
    'cjo': 'unknown',
    'cjs': 'Tiếng Shor',
    'ckb': 'Tiếng Soran',
    'ckh': 'Tiếng Chak',
    'ckt': 'Tiếng Chukot',
    'ckv': 'Tiếng Kavalan',
    'clc': 'Tiếng Chilcotin',
    'clk': 'Tiếng Idu',
    'clm': 'Tiếng Klallam',
    'clt': 'Tiếng Lutuv',
    'clw': 'Tiếng Chulym',
    'cma': 'Tiếng Mạ',
    'cmg': 'Tiếng Mông Cổ cổ điển',
    'cmi': 'Tiếng Emberá-Chamí',
    'cmn': 'Tiếng Quan Thoại',
    'cmo': 'Tiếng M\'Nông Trung',
    'cms': 'Tiếng Messapio',
    'cng': 'Tiếng Khương Bắc',
    'co': 'Tiếng Corse',
    'cod': 'Tiếng Cocama',
    'cog': 'Tiếng Chong',
    'coj': 'Tiếng Cochimi',
    'com': 'Tiếng Comanche',
    'con': 'Tiếng Cofán',
    'coo': 'Tiếng Comox',
    'cop': 'Tiếng Copt',
    'cow': 'Tiếng Cowlitz',
    'cr': 'Tiếng Cree',
    'crh': 'Tiếng Tatar Crưm',
    'crk': 'Tiếng Cree đồng bằng',
    'cro': 'Tiếng Crow',
    'crp-sol': 'Tiếng Anh Solombala',
    'crv': 'Tiếng Chaura',
    'crw': 'Tiếng Chơ Ro',
    'crx': 'Tiếng Carrier',
    'cs': 'Tiếng Séc',
    'csb': 'Tiếng Kaszëb',
    'csj': 'Tiếng Chin Songlai',
    'ctg': 'Tiếng Chittagong',
    'ctp': 'Tiếng Chatino cao nguyên Tây',
    'cts': 'Tiếng Bắc Catanduanes Bikol',
    'cu': 'Tiếng Slav Giáo hội cổ',
    'cua': 'Tiếng Co',
    'cup': 'Tiếng Cupeño',
    'cus-ash': 'Tiếng Ashraaf',
    'cv': 'Tiếng Chuvash',
    'cwg': 'Tiếng Chewong',
    'cy': 'Tiếng Wales',
    'cyo': 'Tiếng Cuyunon',
    'czk': 'Tiếng Knaan',
    'da': 'Tiếng Đan Mạch',
    'daa': 'Tiếng Dangaléat',
    'dag': 'Tiếng Dagbani',
    'dak': 'Tiếng Dakota',
    'dal': 'Tiếng Dahalo',
    'dar': 'Tiếng Dargwa',
    'dbj': 'Tiếng Ida\'an',
    'ddo': 'Tiếng Tsez',
    'de': 'Tiếng Đức',
    'der': 'Tiếng Deori',
    'dgi': 'Tiếng Dagara Bắc',
    'dgr': 'Tiếng Dogrib',
    'dhi': 'Tiếng Dhimal',
    'dhn': 'Tiếng Dhanka',
    'dho': 'Tiếng Dhodia',
    'dhw': 'Tiếng Danuwar',
    'dim': 'Tiếng Dime',
    'din': 'Tiếng Dinka',
    'dis': 'Tiếng Dimasa',
    'dje': 'Tiếng Zarma',
    'dji': 'Tiếng Djinang',
    'dlg': 'Tiếng Dolgan',
    'dlk': 'Tiếng Dahalik',
    'dlm': 'Tiếng Dalmatia',
    'dmg': 'Tiếng Thượng Kinabatangan',
    'dng': 'Tiếng Đông Can',
    'dnj': 'Tiếng Dan',
    'dnu': 'Tiếng Danau',
    'dnv': 'Tiếng Danu',
    'doi': 'Tiếng Dogri',
    'dop': 'Tiếng Lukpa',
    'dra-okn': 'Tiếng Kannada cổ',
    'dre': 'Tiếng Dolpo',
    'drg': 'Tiếng Rungus',
    'drs': 'Tiếng Gedeo',
    'dru': 'Tiếng Rukai',
    'dsb': 'Tiếng Hạ Sorb',
    'dsh': 'Tiếng Daasanach',
    'dso': 'Tiếng Desiya',
    'dta': 'Tiếng Daur',
    'dtd': 'Tiếng Ditidaht',
    'dtp': 'Tiếng Trung Dusun',
    'dty': 'Tiếng Doteli',
    'dub': 'Tiếng Dubla',
    'duh': 'Tiếng Bhil Dungra',
    'dum': 'Tiếng Hà Lan trung đại',
    'dus': 'Tiếng Dumi',
    'duw': 'Tiếng Dusun Witu',
    'dux': 'Tiếng Duun',
    'dv': 'Tiếng Dhivehi',
    'dwk': 'Tiếng Kui Dawik',
    'dwr': 'Tiếng Dawro',
    'dyu': 'Tiếng Dyula',
    'dz': 'Tiếng Dzongkha',
    'ee': 'Tiếng Ewe',
    'efi': 'Tiếng Efik',
    'egl': 'Tiếng Emilia',
    'egx-dem': 'Tiếng Ai Cập bình dân',
    'egy': 'Tiếng Ai Cập',
    'ekl': 'Tiếng Kolhe',
    'eky': 'Tiếng Đông Kayah',
    'el': 'Tiếng Hy Lạp',
    'elo': 'Tiếng El Molo',
    'emp': 'Tiếng Bắc Emberá',
    'en': 'Tiếng Anh',
    'enc': 'Tiếng Nùng Vẻn',
    'enf': 'Tiếng Enets rừng',
    'enh': 'Tiếng Enets lãnh nguyên',
    'enm': 'Tiếng Anh trung đại',
    'eo': 'Tiếng Quốc tế ngữ',
    'eot': 'Tiếng Eotile',
    'es': 'Tiếng Tây Ban Nha',
    'ess': 'Tiếng Yupik Trung Siberia',
    'esu': 'Tiếng Yup\'ik',
    'et': 'Tiếng Estonia',
    'ett': 'Tiếng Etrusca',
    'etu': 'Tiếng Ejagham',
    'eu': 'Tiếng Basque',
    'eve': 'Tiếng Even',
    'evn': 'Tiếng Evenk',
    'fa': 'Tiếng Ba Tư',
    'fax': 'Tiếng Fala',
    'ff': 'Tiếng Fula',
    'fi': 'Tiếng Phần Lan',
    'fia': 'Tiếng Nobiin',
    'fj': 'Tiếng Fiji',
    'fkv': 'Tiếng Kven',
    'fmp': 'Tiếng Fe\'fe\'',
    'fng': 'Tiếng Fanagalo',
    'fo': 'Tiếng Faroe',
    'foi': 'Tiếng Foi',
    'fon': 'Tiếng Fon',
    'fr': 'Tiếng Pháp',
    'frm': 'Tiếng Pháp trung đại',
    'fro': 'Tiếng Pháp cổ',
    'frp': 'Tiếng Franco-Provençal',
    'frr': 'Tiếng Bắc Friesland',
    'fur': 'Tiếng Friuli',
    'fvr': 'Tiếng Fur',
    'fy': 'Tiếng Tây Frisia',
    'ga': 'Tiếng Ireland',
    'gaa': 'Tiếng Ga',
    'gab': 'Tiếng Gabri',
    'gad': 'Tiếng Gaddang',
    'gag': 'Tiếng Gagauz',
    'gah': 'Tiếng Alekano',
    'gan': 'Tiếng Cám',
    'gaq': 'Tiếng Gata\'',
    'gas': 'Tiếng Garasia Adiwasi',
    'gax': 'Tiếng Oromo Nam',
    'gbk': 'Tiếng Gaddi',
    'gbl': 'Tiếng Gamit',
    'gbm': 'Tiếng Garhwal',
    'gcf': 'Tiếng Creole Antilles',
    'gd': 'Tiếng Gael Scotland',
    'gdl': 'Tiếng Dirasha',
    'gdo': 'Tiếng Godoberi',
    'gdq': 'Tiếng Mehri',
    'gej': 'Tiếng Gen',
    'gex': 'Tiếng Garre',
    'gez': 'Tiếng Geʽez',
    'gha': 'Tiếng Ghadames',
    'ghk': 'Tiếng Karen Geko',
    'gii': 'Tiếng Girirra',
    'gil': 'Tiếng Kiribati',
    'gim': 'Tiếng Gimi (Goroka)',
    'gin': 'Tiếng Hinukh',
    'giw': 'Tiếng Cờ Lao Trắng',
    'gjk': 'Tiếng Koli Kachi',
    'gju': 'Tiếng Gujar',
    'gkp': 'Tiếng Kpelle Guinea',
    'gl': 'Tiếng Galicia',
    'glb': 'Tiếng Belnəng',
    'gld': 'Tiếng Nanai',
    'glk': 'Tiếng Gilak',
    'gmh': 'Tiếng Đức cao địa trung đại',
    'gmq-osw': 'Tiếng Thụy Điển cổ',
    'gmv': 'Tiếng Gamo',
    'gmw-cfr': 'Tiếng Franken Trung',
    'gmw-ecg': 'Tiếng Đức Đông Trung',
    'gmw-jdt': 'Tiếng Hà Lan Jersey',
    'gn': 'Tiếng Guaraní',
    'gnc': 'Tiếng Guanche',
    'gof': 'Tiếng Gofa',
    'goh': 'Tiếng Đức cao địa cổ',
    'got': 'Tiếng Goth',
    'gow': 'Tiếng Gorowa',
    'gra': 'Tiếng Garasia Rajput',
    'grc': 'Tiếng Hy Lạp cổ',
    'grh': 'Tiếng Gbiri-Niragu',
    'grt': 'Tiếng Garo',
    'gru': 'Tiếng Kistane',
    'gsw': 'Tiếng Đức Alemanni',
    'gu': 'Tiếng Gujarat',
    'gub': 'Tiếng Guajajára',
    'guk': 'Tiếng Gumuz',
    'gur': 'Tiếng Gurenne',
    'guw': 'Tiếng Gun',
    'gv': 'Tiếng Man',
    'gvj': 'Tiếng Guajá',
    'gwc': 'Tiếng Kalam',
    'gwi': 'Tiếng Gwichʼin',
    'gwt': 'Tiếng Gawar-Bati',
    'gyl': 'Tiếng Gayil',
    'ha': 'Tiếng Hausa',
    'hae': 'Tiếng Oromo Đông',
    'hai': 'Tiếng Haida',
    'haj': 'Tiếng Hajong',
    'hak': 'Tiếng Khách Gia',
    'hal': 'Tiếng Hà Lăng',
    'har': 'Tiếng Harari',
    'haw': 'Tiếng Hawaii',
    'haz': 'Tiếng Hazara',
    'hbn': 'Tiếng Heiban',
    'hdy': 'Tiếng Hadiyya',
    'he': 'Tiếng Do Thái',
    'hei': 'Tiếng Heiltsuk',
    'hi': 'Tiếng Hindi',
    'hif': 'Tiếng Hindi Fiji',
    'hil': 'Tiếng Hiligaynon',
    'hit': 'Tiếng Hitti',
    'hlb': 'Tiếng Halba',
    'hmd': 'Tiếng A-Hmao',
    'hmf': 'Tiếng Mông',
    'hne': 'Tiếng Chhattisgarh',
    'hni': 'Tiếng Hà Nhì',
    'hnn': 'Tiếng Hanunoo',
    'hno': 'Tiếng Hindko Bắc',
    'hoa': 'Tiếng Hoava',
    'hoc': 'Tiếng Ho',
    'hoy': 'Tiếng Holiya',
    'hre': 'Tiếng Hrê',
    'hro': 'Tiếng H\'roi',
    'hrx': 'Tiếng Hunsrik',
    'hsb': 'Tiếng Thượng Sorb',
    'ht': 'Tiếng Haiti',
    'hu': 'Tiếng Hungary',
    'huo': 'Tiếng Hu',
    'hup': 'Tiếng Hupa',
    'huq': 'Tiếng Tsat',
    'hur': 'Tiếng Halkomelem',
    'hus': 'Tiếng Wastek',
    'huz': 'Tiếng Hunzib',
    'hy': 'Tiếng Armenia',
    'hz': 'Tiếng Herero',
    'ia': 'Tiếng Bổ trợ Quốc tế',
    'iai': 'Tiếng Iaai',
    'iba': 'Tiếng Iban',
    'ibb': 'Tiếng Ibibio',
    'ibd': 'Tiếng Iwaidja',
    'ibg': 'Tiếng Ibanag',
    'ibh': 'Tiếng Bih',
    'ibl': 'Tiếng Ibaloi',
    'ibn': 'Tiếng Ibino',
    'ibr': 'Tiếng Ibuoro',
    'ica': 'Tiếng Ede Ica',
    'id': 'Tiếng Indonesia',
    'ife': 'Tiếng Ifè',
    'ig': 'Tiếng Igbo',
    'igl': 'Tiếng Igala',
    'ii': 'Tiếng Lô Lô',
    'ik': 'Tiếng Inupiaq',
    'ili': 'Tiếng Ili Turki',
    'ilo': 'Tiếng Ilokano',
    'inc-kho': 'Tiếng Kholosi',
    'inc-oas': 'Tiếng Assam cận đại',
    'ing': 'Tiếng Deg Xinag',
    'inh': 'Tiếng Ingush',
    'int': 'Tiếng Intha',
    'io': 'Tiếng Ido',
    'ior': 'Tiếng Inor',
    'iow': 'Tiếng Chiwere',
    'irk': 'Tiếng Iraqw',
    'iru': 'Tiếng Irula',
    'is': 'Tiếng Iceland',
    'ish': 'Tiếng Esan',
    'iso': 'Tiếng Isoko',
    'it': 'Tiếng Ý',
    'itl': 'Tiếng Itelmen',
    'itm': 'Tiếng Itu Mbon Uzo',
    'ito': 'Tiếng Itonama',
    'iu': 'Tiếng Inuktitut',
    'ium': 'Tiếng Ưu Miền',
    'ivb': 'Tiếng Ibatan',
    'ivv': 'Tiếng Ivatan',
    'ixl': 'Tiếng Ixil',
    'izh': 'Tiếng Ingria',
    'ja': 'Tiếng Nhật',
    'jaa': 'Tiếng Jamamadí',
    'jab': 'Tiếng Hyam',
    'jac': 'Tiếng Jacaltec',
    'jah': 'Tiếng Jah Hut',
    'jbk': 'Tiếng Barikewa',
    'jbn': 'Tiếng Nefusa',
    'jbo': 'Tiếng Lojban',
    'jct': 'Tiếng Krymchak',
    'jdt': 'Tiếng Tat-Do Thái',
    'jeh': 'Tiếng Giẻ',
    'jgo': 'Tiếng Ngomba',
    'jhi': 'Tiếng Jehai',
    'jii': 'Tiếng Jiiddu',
    'jkm': 'Tiếng Karen Mobwa',
    'jkp': 'Tiếng Karen Paku',
    'jmb': 'Tiếng Zumbun',
    'jnj': 'Tiếng Yemsa',
    'jpx-hcj': 'Tiếng Hachijō',
    'jra': 'Tiếng Gia Rai',
    'juc': 'Tiếng Nữ Chân',
    'jul': 'Tiếng Jirel',
    'jum': 'Tiếng Jumjum',
    'jun': 'Tiếng Juang',
    'jup': 'Tiếng Hupdë',
    'jut': 'Tiếng Jylland',
    'juy': 'Tiếng Juray',
    'jv': 'Tiếng Java',
    'jvd': 'Tiếng Javindo',
    'ka': 'Tiếng Gruzia',
    'kaa': 'Tiếng Karakalpak',
    'kab': 'Tiếng Kabyle',
    'kac': 'Tiếng Kachin',
    'kak': 'Tiếng Kalanguya',
    'kap': 'Tiếng Bezhta',
    'kaq': 'Tiếng Capanahua',
    'kaw': 'Tiếng Java cổ',
    'kbd': 'Tiếng Kabardia',
    'kbg': 'Tiếng Khamba',
    'kbp': 'Tiếng Kabiye',
    'kbr': 'Tiếng Kafa',
    'kca': 'Tiếng Khanty',
    'kca-eas': 'Tiếng Đông Khanty',
    'kcg': 'Tiếng Tyap',
    'kcn': 'Tiếng Nubi',
    'kdh': 'Tiếng Tem',
    'kdq': 'Tiếng Koch',
    'kdr': 'Tiếng Karaim',
    'kdt': 'Tiếng Kuy',
    'kea': 'Tiếng Kabuverdianu',
    'ken': 'Tiếng Kenyang',
    'ket': 'Tiếng Ket',
    'kex': 'Tiếng Kukna',
    'kfa': 'Tiếng Kodava',
    'kfb': 'Tiếng Kolami',
    'kfc': 'Tiếng Konda-Dora',
    'kfd': 'Tiếng Koraga Korra',
    'kff': 'Tiếng Koya',
    'kfg': 'Tiếng Kudiya',
    'kfh': 'Tiếng Kurichiya',
    'kfi': 'Tiếng Kurumba Kannada',
    'kfk': 'Tiếng Kinnaur',
    'kfq': 'Tiếng Korku',
    'kfr': 'Tiếng Kutch',
    'kfs': 'Tiếng Bilaspur',
    'kfx': 'Tiếng Kullu',
    'kgj': 'Tiếng Kham Gamale',
    'kgp': 'Tiếng Kaingang',
    'kha': 'Tiếng Khasi',
    'khb': 'Tiếng Lự',
    'khc': 'Tiếng Tukang Besi Bắc',
    'khf': 'Tiếng Khuen',
    'khg': 'Tiếng Tây Tạng Kham',
    'khr': 'Tiếng Kharia',
    'kht': 'Tiếng Khamti',
    'khv': 'Tiếng Khvarshi',
    'khw': 'Tiếng Khowar',
    'ki': 'Tiếng Gikuyu',
    'kib': 'Tiếng Koalib',
    'kif': 'Tiếng Kham Parbate Đông',
    'kim': 'Tiếng Tofa',
    'kio': 'Tiếng Kiowa',
    'kip': 'Tiếng Kham Sheshi',
    'kix': 'Tiếng Khiamniungan',
    'kjg': 'Tiếng Khơ Mú',
    'kjh': 'Tiếng Khakas',
    'kjj': 'Tiếng Khinalug',
    'kjl': 'Tiếng Kham Parbate Tây',
    'kjm': 'Tiếng Kháng',
    'kjp': 'Tiếng Pwo Đông',
    'kjt': 'Tiếng Pwo Phrae',
    'kju': 'Tiếng Kashaya',
    'kk': 'Tiếng Kazakh',
    'kkh': 'Tiếng Khün',
    'kkv': 'Tiếng Kangean',
    'kl': 'Tiếng Greenland',
    'klj': 'Tiếng Khalaj',
    'klr': 'Tiếng Khaling',
    'kls': 'Tiếng Kalash',
    'klw': 'Tiếng Lindu',
    'kly': 'Tiếng Kalao',
    'km': 'Tiếng Khmer',
    'kmc': 'Tiếng Nam Động',
    'kmj': 'Tiếng Paharia Kumarbhag',
    'kmk': 'Tiếng Kalinga Limos',
    'kmr': 'Tiếng Kurmanji',
    'kmz': 'Tiếng Turk Khorasan',
    'kn': 'Tiếng Kannada',
    'kne': 'Tiếng Kankanaey',
    'knp': 'Tiếng Kwanja',
    'knq': 'Tiếng Kintaq',
    'kns': 'Tiếng Kensiu',
    'ko': 'Tiếng Triều Tiên',
    'koi': 'Tiếng Komi-Permyak',
    'kok': 'Tiếng Konkan',
    'kpb': 'Tiếng Kurumba Mullu',
    'kpg': 'Tiếng Kapingamarangi',
    'kpm': 'Tiếng K\'Ho',
    'kpo': 'Tiếng Ikposo',
    'kpt': 'Tiếng Karata',
    'kpv': 'Tiếng Komi-Zyrian',
    'kpw': 'Tiếng Kobon',
    'kpy': 'Tiếng Koryak',
    'kqf': 'Tiếng Kakabai',
    'kqy': 'Tiếng Koore',
    'kr': 'Tiếng Kanuri',
    'krc': 'Tiếng Karachay-Balkar',
    'kri': 'Tiếng Krio',
    'krl': 'Tiếng Karelia',
    'krr': 'Tiếng Krung',
    'krs': 'Tiếng Kresh',
    'kru': 'Tiếng Kurukh',
    'krv': 'Tiếng Kavet',
    'kry': 'Tiếng Kryts',
    'ks': 'Tiếng Kashmir',
    'ksu': 'Tiếng Khamyang',
    'ksw': 'Tiếng Karen S\'gaw',
    'kta': 'Tiếng Ca Tua',
    'ktb': 'Tiếng Kambaata',
    'ktn': 'Tiếng Karitiâna',
    'ktu': 'Tiếng Kituba',
    'ktv': 'Tiếng Cơ Tu',
    'ktz': 'Tiếng Juǀ\'hoan',
    'ku': 'Tiếng Kurd',
    'kud': 'Tiếng Auhelawa',
    'kuf': 'Tiếng Cơ Tu Tây',
    'kum': 'Tiếng Kumyk',
    'kut': 'Tiếng Ktunaxa',
    'kva': 'Tiếng Bagvalal',
    'kvq': 'Tiếng Karen Geba',
    'kvt': 'Tiếng Lahta',
    'kvx': 'Tiếng Koli Parkar',
    'kw': 'Tiếng Cornwall',
    'kwk': 'Tiếng Kwak\'wala',
    'kxc': 'Tiếng Konso',
    'kxd': 'Tiếng Mã Lai Brunei',
    'kxf': 'Tiếng Manumanaw',
    'kxh': 'Tiếng Karo',
    'kxk': 'Tiếng Karen Zayein',
    'kxm': 'Tiếng Khmer Surin',
    'kxp': 'Tiếng Koli Wadiyara',
    'kxs': 'Tiếng Khang Gia',
    'kxv': 'Tiếng Kuvi',
    'kxy': 'Tiếng Ca Dong',
    'ky': 'Tiếng Kyrgyz',
    'kyj': 'Tiếng Karao',
    'kyk': 'Tiếng Kamayo',
    'kyu': 'Tiếng Tây Kayah',
    'kyv': 'Tiếng Kayort',
    'kyw': 'Tiếng Kudmal',
    'kzg': 'Tiếng Kikai',
    'la': 'Tiếng Latinh',
    'lad': 'Tiếng Ladino',
    'lah': 'Tiếng Lahnda',
    'las': 'Tiếng Lama Gur',
    'lax': 'Tiếng Tiwa',
    'lb': 'Tiếng Luxembourg',
    'lbe': 'Tiếng Lak',
    'lbj': 'Tiếng Ladakh',
    'lbo': 'Tiếng Jru\'',
    'lcp': 'Tiếng Lawa Tây',
    'lef': 'Tiếng Lelemi',
    'lep': 'Tiếng Lepcha',
    'lez': 'Tiếng Lezgi',
    'lhu': 'Tiếng La Hủ',
    'li': 'Tiếng Limburg',
    'lic': 'Tiếng Hlai',
    'lij': 'Tiếng Liguria',
    'liq': 'Tiếng Libido',
    'liv': 'Tiếng Livonia',
    'lix': 'Tiếng Liabuku',
    'lki': 'Tiếng Laki',
    'lkt': 'Tiếng Lakota',
    'lld': 'Tiếng Ladin',
    'llm': 'Tiếng Lasalimu',
    'lmn': 'Tiếng Lambadi',
    'lmo': 'Tiếng Lombard',
    'lmp': 'Tiếng Limbum',
    'lmy': 'Tiếng Lamboya',
    'ln': 'Tiếng Lingala',
    'lo': 'Tiếng Lào',
    'lob': 'Tiếng Lobi',
    'loj': 'Tiếng Lou',
    'lou': 'Tiếng Creole Louisiana',
    'loy': 'Tiếng Loke',
    'lrc': 'Tiếng Lur Bắc',
    'lrl': 'Tiếng Lar',
    'lsi': 'Tiếng Lashi',
    'lt': 'Tiếng Litva',
    'ltg': 'Tiếng Latgale',
    'ltn': 'Tiếng Latundê',
    'lud': 'Tiếng Lyydi',
    'luo': 'Tiếng Luo',
    'lus': 'Tiếng Mizo',
    'lut': 'Tiếng Lushootseed',
    'luz': 'Tiếng Lur Nam',
    'lv': 'Tiếng Latvia',
    'lvi': 'Tiếng Lawi',
    'lvk': 'Tiếng Lavukaleve',
    'lwl': 'Tiếng Lawa Đông',
    'lwm': 'Tiếng Laomian',
    'lyg': 'Tiếng Lyngngam',
    'lzz': 'Tiếng Laz',
    'mad': 'Tiếng Madura',
    'mag': 'Tiếng Magaha',
    'mai': 'Tiếng Maithil',
    'mas': 'Tiếng Maasai',
    'max': 'Tiếng Mã Lai Bắc Maluku',
    'maz': 'Tiếng Mazahua Trung',
    'mba': 'Tiếng Higaonon',
    'mbd': 'Tiếng Dibabawon',
    'mbf': 'Tiếng Mã Lai Baba',
    'mby': 'Tiếng Memon',
    'mch': 'Tiếng Ye\'kwana',
    'mcq': 'Tiếng Ese',
    'mde': 'Tiếng Mabang',
    'mdf': 'Tiếng Moksha',
    'mdh': 'Tiếng Maguindanao',
    'mdx': 'Tiếng Dizi',
    'mdy': 'Tiếng Maale',
    'med': 'Tiếng Melpa',
    'men': 'Tiếng Mende',
    'meo': 'Tiếng Mã Lai Kedah',
    'mew': 'Tiếng Maaka',
    'mez': 'Tiếng Menominee',
    'mfa': 'Tiếng Mã Lai Pattani',
    'mfe': 'Tiếng Creole Mauritius',
    'mfx': 'Tiếng Melo',
    'mg': 'Tiếng Malagasy',
    'mgc': 'Tiếng Morokodo',
    'mgp': 'Tiếng Magar Đông',
    'mh': 'Tiếng Marshall',
    'mha': 'Tiếng Manda (Ấn Độ)',
    'mhe': 'Tiếng Mah Meri',
    'mhj': 'Tiếng Mogholi',
    'mhr': 'Tiếng Mari Đông',
    'mht': 'Tiếng Mandahuaca',
    'mhy': 'Tiếng Ma\'anyan',
    'mi': 'Tiếng Maori',
    'mic': 'Tiếng Mi\'kmaq',
    'mih': 'Tiếng Mixtec Chayuco',
    'min': 'Tiếng Minangkabau',
    'mji': 'Tiếng Kim Môn',
    'mjl': 'Tiếng Mandi',
    'mjr': 'Tiếng Malavedan',
    'mjt': 'Tiếng Paharia Sauria',
    'mjv': 'Tiếng Mannan',
    'mjw': 'Tiếng Karbi',
    'mjx': 'Tiếng Mahal',
    'mk': 'Tiếng Macedoni',
    'mkh-bhn': 'Tiếng Bhnong',
    'mkh-mmn': 'Tiếng Môn trung đại',
    'mkh-mvi': 'Tiếng Việt trung cổ',
    'mki': 'Tiếng Dhatki',
    'mkm': 'Tiếng Moklen',
    'ml': 'Tiếng Malayalam',
    'mlf': 'Tiếng Mal',
    'mlv': 'Tiếng Mwotlap',
    'mmc': 'Tiếng Mazahua Michoacán',
    'mn': 'Tiếng Mông Cổ',
    'mnb': 'Tiếng Muna',
    'mnc': 'Tiếng Mãn Châu',
    'mng': 'Tiếng M\'Nông Đông',
    'mni': 'Tiếng Manipur',
    'mnj': 'Tiếng Munji',
    'mnk': 'Tiếng Mandinka',
    'mnn': 'Tiếng M\'Nông Nam',
    'mnq': 'Tiếng Minriq',
    'mns-cen': 'Tiếng Trung Mansi',
    'mns-nor': 'Tiếng Bắc Mansi',
    'mns-sou': 'Tiếng Nam Mansi',
    'mnw': 'Tiếng Môn',
    'mnw-tha': 'Tiếng Môn Thái',
    'mog': 'Tiếng Mongondow',
    'moo': 'Tiếng Mơ Nâm',
    'mor': 'Tiếng Moro',
    'mos': 'Tiếng Mooré',
    'mpe': 'Tiếng Majang',
    'mpi': 'Tiếng Mpade',
    'mpz': 'Tiếng Mpi',
    'mqs': 'Tiếng Tây Makian',
    'mr': 'Tiếng Marathi',
    'mra': 'Tiếng Mlabri',
    'mrd': 'Tiếng Magar Tây',
    'mrj': 'Tiếng Mari Tây',
    'mrw': 'Tiếng Maranao',
    'ms': 'Tiếng Mã Lai',
    'msb': 'Tiếng Masbatenyo',
    'msk': 'Tiếng Mansaka',
    'msn': 'Tiếng Vurës',
    'mt': 'Tiếng Malta',
    'mtm': 'Tiếng Mator',
    'mtq': 'Tiếng Mường',
    'mul': 'Đa ngữ',
    'mur': 'Tiếng Murle',
    'mus': 'Tiếng Muscogee',
    'muu': 'Tiếng Yaaku',
    'muv': 'Tiếng Muthuvan',
    'muz': 'Tiếng Mursi',
    'mvi': 'Tiếng Miyako',
    'mvv': 'Tiếng Tagal Murut',
    'mvy': 'Tiếng Kohistan',
    'mwl': 'Tiếng Miranda',
    'mwr': 'Tiếng Marwar',
    'mwt': 'Tiếng Moken',
    'mwv': 'Tiếng Mentawai',
    'mww': 'Tiếng Mông Trắng',
    'mxi': 'Tiếng Mozarab',
    'my': 'Tiếng Miến Điện',
    'myf': 'Tiếng Bambassi',
    'mym': 'Tiếng Me\'en',
    'myv': 'Tiếng Erzya',
    'mzb': 'Tiếng Berber Bắc Sahara',
    'mzn': 'Tiếng Mazandaran',
    'mzt': 'Tiếng Mintil',
    'na': 'Tiếng Nauru',
    'nab': 'Tiếng Nambikwara',
    'nai-kum': 'Tiếng Kumeyaay',
    'nai-tip': 'Tiếng Tipai',
    'nan': 'Tiếng Mân Nam',
    'nan-hbl': 'Tiếng Mân Tuyền Chương',
    'nap': 'Tiếng Napoli',
    'naq': 'Tiếng Khoekhoe',
    'nb': 'Tiếng Na Uy (Bokmål)',
    'ncb': 'Tiếng Nicobar Trung',
    'nch': 'Tiếng Trung Nahuatl Huasteca',
    'nci': 'Tiếng Nahuatl cổ điển',
    'ncq': 'Tiếng Katang Bắc',
    'nct': 'Tiếng Naga Chothe',
    'nd': 'Tiếng Bắc Ndebele',
    'nds': 'Tiếng Hạ Đức',
    'nds-de': 'Tiếng Hạ Đức tại Đức',
    'nds-nl': 'Tiếng Hạ Saxon Hà Lan',
    'ne': 'Tiếng Nepal',
    'neg': 'Tiếng Negidal',
    'neo': 'Tiếng Na Miểu',
    'new': 'Tiếng Newa',
    'nfr': 'Tiếng Nafaanra',
    'ng': 'Tiếng Ndonga',
    'ngh': 'Tiếng Nǀuu',
    'nhn': 'Tiếng Trung Nahuatl',
    'nhv': 'Tiếng Nahuatl Temascaltepec',
    'nik': 'Tiếng Nicobar Nam',
    'nio': 'Tiếng Nganasan',
    'nit': 'Tiếng Nam Kolami',
    'niu': 'Tiếng Niue',
    'niv': 'Tiếng Nivkh',
    'njm': 'Tiếng Angami',
    'nko': 'Tiếng Nkonya',
    'nkz': 'Tiếng Nkari',
    'nl': 'Tiếng Hà Lan',
    'nn': 'Tiếng Na Uy (Nynorsk)',
    'nnh': 'Tiếng Ngiemboon',
    'nnk': 'Tiếng Nankina',
    'nnp': 'Tiếng Wancho',
    'no': 'Tiếng Na Uy',
    'nod': 'Tiếng Bắc Thái',
    'nog': 'Tiếng Nogai',
    'non': 'Tiếng Bắc Âu cổ',
    'nr': 'Tiếng Nam Ndebele',
    'nrc': 'Tiếng Noreia',
    'nrf': 'Tiếng Norman',
    'nrp': 'Tiếng Piceni Bắc',
    'nru': 'Tiếng Ma Thoa',
    'nso': 'Tiếng Sotho Bắc',
    'ntp': 'Tiếng Tepehuan Bắc',
    'nuk': 'Tiếng Nuu-chah-nulth',
    'nuo': 'Tiếng Nguồn',
    'nus': 'Tiếng Nuer',
    'nut': 'Tiếng Nùng',
    'nv': 'Tiếng Navajo',
    'ny': 'Tiếng Chichewa',
    'nyl': 'Tiếng Nyeu',
    'nyw': 'Tiếng Nyaw',
    'nzd': 'Tiếng Nzadi',
    'oaa': 'Tiếng Orok',
    'oac': 'Tiếng Oroch',
    'oc': 'Tiếng Occitan',
    'ocm': 'Tiếng Chăm cổ',
    'oge': 'Tiếng Gruzia cổ',
    'ogu': 'Tiếng Ogbronuagum',
    'oj': 'Tiếng Ojibwe',
    'ojp': 'Tiếng Nhật cổ',
    'oka': 'Tiếng Okanagan',
    'okm': 'Tiếng Triều Tiên trung đại',
    'okn': 'Tiếng Okinoerabu',
    'okz': 'Tiếng Khmer cổ',
    'olo': 'Tiếng Livvi',
    'om': 'Tiếng Oromo',
    'omk': 'Tiếng Omok',
    'omx': 'Tiếng Môn cổ',
    'omy': 'Tiếng Mã Lai cổ',
    'ood': 'Tiếng O\'odham',
    'or': 'Tiếng Oriya',
    'orc': 'Tiếng Orma',
    'orh': 'Tiếng Oroqen',
    'ort': 'Tiếng Oriya Adiwasi',
    'oru': 'Tiếng Ormur',
    'orv': 'Tiếng Slav Đông cổ',
    'os': 'Tiếng Ossetia',
    'osa': 'Tiếng Osage',
    'osc': 'Tiếng Osci',
    'osn': 'Tiếng Sunda cổ',
    'osp': 'Tiếng Tây Ban Nha cổ',
    'ota': 'Tiếng Thổ Nhĩ Kỳ Ottoman',
    'ote': 'Tiếng Otomi Mezquital',
    'otk': 'Tiếng Turk cổ',
    'oui': 'Tiếng Duy Ngô Nhĩ cổ',
    'ovd': 'Tiếng Övdal',
    'oyd': 'Tiếng Oyda',
    'ozm': 'Tiếng Koonzime',
    'pa': 'Tiếng Punjab',
    'pab': 'Tiếng Pareci',
    'pac': 'Tiếng Pa Kô',
    'pag': 'Tiếng Pangasinan',
    'pam': 'Tiếng Kapampangan',
    'pao': 'Tiếng Bắc Paiute',
    'pap': 'Tiếng Papiamento',
    'pau': 'Tiếng Palau',
    'pbv': 'Tiếng Pnar',
    'pcb': 'Tiếng Pear',
    'pcc': 'Tiếng Bố Y',
    'pcd': 'Tiếng Picard',
    'pce': 'Tiếng Palaung Ruching',
    'pcg': 'Tiếng Paniya',
    'pci': 'Tiếng Duruwa',
    'pdc': 'Tiếng Đức Pennsylvania',
    'pdt': 'Tiếng Hạ Đức Mennonite',
    'pea': 'Tiếng Indonesia Peranakan',
    'peg': 'Tiếng Pengo',
    'peh': 'Tiếng Bảo An',
    'peo': 'Tiếng Ba Tư cổ',
    'pga': 'Tiếng Ả Rập Juba',
    'pgg': 'Tiếng Pangwala',
    'pha': 'Tiếng Pà Thẻn',
    'phg': 'Tiếng Cơ Tu Phương',
    'phk': 'Tiếng Phake',
    'phl': 'Tiếng Phalura',
    'phr': 'Tiếng Pothohar',
    'pht': 'Tiếng Phu Thái',
    'phu': 'Tiếng Phuan',
    'pi': 'Tiếng Pali',
    'pil': 'Tiếng Yom',
    'pjt': 'Tiếng Pitjantjatjara',
    'pkr': 'Tiếng Kurumba Attapady',
    'pku': 'Tiếng Paku',
    'pl': 'Tiếng Ba Lan',
    'plk': 'Tiếng Shina Kohistan',
    'pll': 'Tiếng Palaung Shwe',
    'plw': 'Tiếng Palawano Brooke\'s Point',
    'ply': 'Tiếng Bố Lưu',
    'pnk': 'Tiếng Pauna',
    'pnp': 'Tiếng Pancana',
    'pns': 'Tiếng Ponosakan',
    'pnt': 'Tiếng Hy Lạp Pontos',
    'pny': 'Tiếng Pinyin',
    'pon': 'Tiếng Pohnpei',
    'pov': 'Tiếng Creole Guinea-Bissau',
    'pox': 'Tiếng Polabia',
    'poz-abi': 'Tiếng Abai',
    'ppl': 'Tiếng Pipil',
    'pra': 'Tiếng Prakrit',
    'prg': 'Tiếng Phổ cổ',
    'prk': 'Tiếng Parauk',
    'prt': 'Tiếng Phai',
    'ps': 'Tiếng Pashtun',
    'pt': 'Tiếng Bồ Đào Nha',
    'puo': 'Tiếng Xinh Mun',
    'pwm': 'Tiếng Molbog',
    'pwn': 'Tiếng Paiwan',
    'pwo': 'Tiếng Pwo Tây',
    'pww': 'Tiếng Pwo Bắc',
    'pyu': 'Tiếng Puyuma',
    'qfa-xgx-tuh': 'Tiếng Thổ Dục Hồn',
    'qfa-xgx-tuo': 'Tiếng Thác Bạt',
    'qu': 'Tiếng Quechua',
    'qua': 'Tiếng Quapaw',
    'qwm': 'Tiếng Cuman',
    'qxq': 'Tiếng Qashqai',
    'rab': 'Tiếng Camling',
    'rad': 'Tiếng Ê Đê',
    'rah': 'Tiếng Rabha',
    'rap': 'Tiếng Rapa Nui',
    'rar': 'Tiếng Rarotonga',
    'rau': 'Tiếng Raute',
    'raw': 'Tiếng Rawang',
    'rbb': 'Tiếng Palaung Rumai',
    'rej': 'Tiếng Rejang',
    'rel': 'Tiếng Rendille',
    'ren': 'Tiếng Rơ Ngao',
    'rgn': 'Tiếng Romagnol',
    'rgs': 'Tiếng Ra Glai Nam',
    'rhg': 'Tiếng Rohingya',
    'rif': 'Tiếng Tarifit',
    'rjs': 'Tiếng Rajbanshi',
    'rka': 'Tiếng Kraol',
    'rki': 'Tiếng Rakhine',
    'rkt': 'Tiếng Rangpur',
    'rm': 'Tiếng Romansh',
    'rma': 'Tiếng Rama',
    'rmf': 'Tiếng Kalo Phần Lan',
    'rmt': 'Tiếng Domari',
    'rmx': 'Tiếng Rơ Măm',
    'rmz': 'Tiếng Marma',
    'ro': 'Tiếng Rumani',
    'roa-brg': 'Tiếng Bourguignon',
    'roa-leo': 'Tiếng León',
    'roa-lor': 'Tiếng Lorrain',
    'roa-oca': 'Tiếng Catalan cổ',
    'roa-opt': 'Tiếng Galicia-Bồ Đào Nha',
    'roa-tar': 'Tiếng Tarantino',
    'roc': 'Tiếng Ra Glai Cát Gia',
    'rog': 'Tiếng Ra Glai Bắc',
    'rom': 'Tiếng Digan',
    'rsk': 'Tiếng Rusnak',
    'ru': 'Tiếng Nga',
    'rue': 'Tiếng Rusyn',
    'ruo': 'Tiếng Istria Rumani',
    'rup': 'Tiếng Aromania',
    'ruq': 'Tiếng Moglena-Rumani',
    'rut': 'Tiếng Rutul',
    'ryn': 'Tiếng Bắc Amami Ōshima',
    'rys': 'Tiếng Yaeyama',
    'ryu': 'Tiếng Okinawa',
    'sa': 'Tiếng Phạn',
    'sah': 'Tiếng Yakut',
    'sai-bag': 'Tiếng Bagua',
    'sai-hau': 'Tiếng Haush',
    'sat': 'Tiếng Santal',
    'saz': 'Tiếng Saurashtra',
    'sc': 'Tiếng Sardegna',
    'sce': 'Tiếng Đông Hương',
    'sck': 'Tiếng Sadri',
    'scl': 'Tiếng Shina',
    'scn': 'Tiếng Sicily',
    'sco': 'Tiếng Scots',
    'scp': 'Tiếng Yolmo',
    'scx': 'Tiếng Sicel',
    'sd': 'Tiếng Sindh',
    'sdb': 'Tiếng Shabak',
    'sdg': 'Tiếng Savi',
    'se': 'Tiếng Bắc Sami',
    'sea': 'Tiếng Semai',
    'sec': 'Tiếng Sechelt',
    'sed': 'Tiếng Xơ Đăng',
    'see': 'Tiếng Seneca',
    'sei': 'Tiếng Seri',
    'sel': 'Tiếng Selkup',
    'sel-nor': 'Tiếng Bắc Selkup',
    'sem-tay': 'Tiếng Tayma',
    'ses': 'Tiếng Senni Koyraboro',
    'sev': 'Tiếng Senoufo Nyarafolo',
    'sg': 'Tiếng Sango',
    'sga': 'Tiếng Ireland cổ',
    'sgh': 'Tiếng Shughnan',
    'sgr': 'Tiếng Sangisar',
    'sgs': 'Tiếng Samogitia',
    'sgw': 'Tiếng Sebat Bet Gurage',
    'sh': 'Tiếng Serbia-Croatia',
    'shd': 'Tiếng Kundal Shahi',
    'shi': 'Tiếng Tashelhit',
    'shn': 'Tiếng Shan',
    'shs': 'Tiếng Shuswap',
    'shu': 'Tiếng Ả Rập Tchad',
    'shy': 'Tiếng Tachawit',
    'si': 'Tiếng Sinhala',
    'sia': 'Tiếng Sami Akkala',
    'sid': 'Tiếng Sidamo',
    'sii': 'Tiếng Shompen',
    'sip': 'Tiếng Sikkim',
    'sit-jap': 'Tiếng Japhug',
    'siz': 'Tiếng Siwi',
    'sjd': 'Tiếng Sami Kildin',
    'sjo': 'Tiếng Tích Bá',
    'sjp': 'Tiếng Surjapur',
    'sjs': 'Tiếng Senhaja De Srair',
    'sjt': 'Tiếng Sami Ter',
    'sk': 'Tiếng Slovak',
    'skb': 'Tiếng Saek',
    'skr': 'Tiếng Saraiki',
    'sl': 'Tiếng Slovene',
    'sle': 'Tiếng Sholaga',
    'slr': 'Tiếng Salar',
    'sm': 'Tiếng Samoa',
    'sma': 'Tiếng Nam Sami',
    'smh': 'Tiếng Thát Mai',
    'smn': 'Tiếng Sami Inari',
    'sms': 'Tiếng Sami Skolt',
    'sn': 'Tiếng Shona',
    'sne': 'Tiếng Singai',
    'snf': 'Tiếng Noon',
    'so': 'Tiếng Somali',
    'soa': 'Tiếng Thái Tống',
    'sog': 'Tiếng Sogdia',
    'sou': 'Tiếng Nam Thái',
    'spx': 'Tiếng Piceni Nam',
    'sq': 'Tiếng Albani',
    'sqt': 'Tiếng Socotra',
    'srb': 'Tiếng Sora',
    'srn': 'Tiếng Sranan Tongo',
    'srr': 'Tiếng Serer',
    'ss': 'Tiếng Swazi',
    'ssm': 'Tiếng Semnam',
    'ssn': 'Tiếng Waata',
    'sss': 'Tiếng Sô',
    'ssy': 'Tiếng Saho',
    'st': 'Tiếng Sotho',
    'sti': 'Tiếng Xtiêng',
    'stp': 'Tiếng Tepehuan Đông Nam',
    'stq': 'Tiếng Frisia Saterland',
    'str': 'Tiếng Saanich',
    'stt': 'Tiếng Xtiêng Bù Đeh',
    'stu': 'Tiếng Samtao',
    'stv': 'Tiếng Siltʼe',
    'sty': 'Tiếng Tatar Siberia',
    'su': 'Tiếng Sunda',
    'suq': 'Tiếng Suri',
    'sux': 'Tiếng Sumer',
    'sv': 'Tiếng Thụy Điển',
    'sva': 'Tiếng Svan',
    'sw': 'Tiếng Swahili',
    'swb': 'Tiếng Comoros Maore',
    'swn': 'Tiếng Sokna',
    'sxn': 'Tiếng Sangir',
    'sxr': 'Tiếng Saaroa',
    'sxw': 'Tiếng Gbe Saxwe',
    'syl': 'Tiếng Sylhet',
    'sza': 'Tiếng Semelai',
    'szb': 'Tiếng Ngalum',
    'szc': 'Tiếng Semaq Beri',
    'sze': 'Tiếng Seze',
    'szl': 'Tiếng Silesia',
    'szy': 'Tiếng Sakizaya',
    'ta': 'Tiếng Tamil',
    'tab': 'Tiếng Tabasaran',
    'taf': 'Tiếng Tapirapé',
    'taj': 'Tiếng Tamang Đông',
    'tao': 'Tiếng Yami',
    'tay': 'Tiếng Atayal',
    'tbz': 'Tiếng Tammari',
    'tco': 'Tiếng Taungyo',
    'tcx': 'Tiếng Toda',
    'tcy': 'Tiếng Tulu',
    'tdb': 'Tiếng Panchpargania',
    'tdc': 'Tiếng Emberá-Tadó',
    'tdd': 'Tiếng Thái Na',
    'tdg': 'Tiếng Tamang Tây',
    'tdr': 'Tiếng Tơ Đrá',
    'tdy': 'Tiếng Tadyawan',
    'te': 'Tiếng Telugu',
    'tea': 'Tiếng Temiar',
    'tef': 'Tiếng Teressa',
    'tet': 'Tiếng Tetum',
    'tft': 'Tiếng Ternate',
    'tg': 'Tiếng Tajik',
    'tge': 'Tiếng Tamang Gorkha Đông',
    'th': 'Tiếng Thái',
    'thm': 'Tiếng Thavưng',
    'thp': 'Tiếng Thompson',
    'ti': 'Tiếng Tigrinya',
    'tig': 'Tiếng Tigre',
    'tin': 'Tiếng Tindi',
    'tiy': 'Tiếng Tiruray',
    'tji': 'Tiếng Thổ Gia Bắc',
    'tjl': 'Tiếng Thái Lai',
    'tjs': 'Tiếng Thổ Gia Nam',
    'tk': 'Tiếng Turkmen',
    'tkl': 'Tiếng Tokelau',
    'tkr': 'Tiếng Tsakhur',
    'tl': 'Tiếng Tagalog',
    'tli': 'Tiếng Tlingit',
    'tlq': 'Tiếng Tai Loi',
    'tly': 'Tiếng Talysh',
    'tmh': 'Tiếng Tuareg',
    'tmo': 'Tiếng Temoq',
    'tn': 'Tiếng Tswana',
    'tnv': 'Tiếng Tanchangya',
    'tnz': 'Tiếng Ten\'edn',
    'to': 'Tiếng Tonga',
    'tok': 'Toki Pona',
    'tou': 'Tiếng Thổ',
    'tpe': 'Tiếng Tippera',
    'tpi': 'Tiếng Tok Pisin',
    'tpn': 'Tiếng Tupi',
    'tpo': 'Tiếng Thái Hàng Tổng',
    'tpu': 'Tiếng Tampuan',
    'tpw': 'Tiếng Tupi cổ',
    'tqq': 'Tiếng Tunni',
    'tr': 'Tiếng Thổ Nhĩ Kỳ',
    'trk-dkh': 'Tiếng Dukha',
    'trk-fyk': 'Tiếng Kyrgyz Phú Dụ',
    'trk-oat': 'Tiếng Thổ Nhĩ Kỳ Anatolia cổ',
    'trk-soy': 'Tiếng Soyot',
    'trp': 'Tiếng Kok Borok',
    'trq': 'Tiếng Triqui San Martín Itunyoso',
    'trs': 'Tiếng Triqui Chicahuaxtla',
    'trw': 'Tiếng Torwali',
    'tsb': 'Tiếng Tsamai',
    'tsg': 'Tiếng Tausug',
    'tsi': 'Tiếng Tsimshian',
    'tsj': 'Tiếng Tshangla',
    'tsu': 'Tiếng Tsou',
    'tt': 'Tiếng Tatar',
    'tth': 'Tiếng Tà Ôi Thượng',
    'ttj': 'Tiếng Tooro',
    'tts': 'Tiếng Isan',
    'tum': 'Tiếng Tumbuka',
    'tuw-alk': 'Tiếng Alchuka',
    'tuw-bal': 'Tiếng Bala',
    'tuw-kkl': 'Tiếng Kyakala',
    'tuw-sol': 'Tiếng Solon',
    'tvl': 'Tiếng Tuvalu',
    'tvn': 'Tiếng Tavoy',
    'tvx': 'Tiếng Taivoan',
    'twh': 'Tiếng Thái Trắng',
    'twq': 'Tiếng Tasawaq',
    'txb': 'Tiếng Tochari B',
    'txg': 'Tiếng Tangut',
    'txo': 'Tiếng Toto',
    'ty': 'Tiếng Tahiti',
    'tyh': 'Tiếng Ơ Đu',
    'tyj': 'Tiếng Tay Dọ',
    'tyr': 'Tiếng Thái Đỏ',
    'tyv': 'Tiếng Tuva',
    'tyz': 'Tiếng Tày',
    'tzm': 'Tiếng Tamazight Trung Atlas',
    'ubl': 'Tiếng Bikol Buhi\'non',
    'uby': 'Tiếng Ubykh',
    'ude': 'Tiếng Udihe',
    'udg': 'Tiếng Muduga',
    'udi': 'Tiếng Udi',
    'udm': 'Tiếng Udmurt',
    'udu': 'Tiếng Uduk',
    'ug': 'Tiếng Duy Ngô Nhĩ',
    'uga': 'Tiếng Ugarit',
    'ugh': 'Tiếng Kubachi',
    'ugo': 'Tiếng Ugong',
    'uk': 'Tiếng Ukraina',
    'uki': 'Tiếng Kui (Ấn Độ)',
    'ukk': 'Tiếng Muak Sa-aak',
    'ulc': 'Tiếng Ulch',
    'ulk': 'Tiếng Meriam',
    'umb': 'Tiếng Umbundu',
    'umu': 'Tiếng Munsee',
    'unr': 'Tiếng Mundari',
    'unx': 'Tiếng Munda',
    'ur': 'Tiếng Urdu',
    'urj-koo': 'Tiếng Komi cổ',
    'urk': 'Tiếng Urak Lawoi\'',
    'url': 'Tiếng Urali',
    'ush': 'Tiếng Ushojo',
    'usi': 'Tiếng Usui',
    'uum': 'Tiếng Urum',
    'uz': 'Tiếng Uzbek',
    'uzs': 'Tiếng Nam Uzbek',
    'vaa': 'Tiếng Vaagri Booli',
    'vas': 'Tiếng Vasavi',
    'vav': 'Tiếng Varli',
    've': 'Tiếng Venda',
    'vec': 'Tiếng Veneto',
    'vep': 'Tiếng Veps',
    'vgr': 'Tiếng Vaghri',
    'vi': 'Tiếng Việt',
    'vmd': 'Tiếng Koraga Mudu',
    'vo': 'Tiếng Volapük',
    'vot': 'Tiếng Vot',
    'vro': 'Tiếng Võro',
    'wa': 'Tiếng Wallon',
    'wal': 'Tiếng Wolaytta',
    'war': 'Tiếng Waray',
    'wbj': 'Tiếng Alagwa',
    'wbl': 'Tiếng Wakhi',
    'wci': 'Tiếng Gbe Waci',
    'wea': 'Tiếng Wewaw',
    'wgi': 'Tiếng Wahgi',
    'win': 'Tiếng Hocak',
    'wiy': 'Tiếng Wiyot',
    'wlm': 'Tiếng Wales trung đại',
    'wlo': 'Tiếng Wolio',
    'wls': 'Tiếng Wallis',
    'wme': 'Tiếng Wambule',
    'wne': 'Tiếng Waneci',
    'wo': 'Tiếng Wolof',
    'wob': 'Tiếng Wobé',
    'wow': 'Tiếng Wawonii',
    'wtw': 'Tiếng Wotu',
    'wuh': 'Tiếng Ngũ Đồn',
    'wuu': 'Tiếng Ngô',
    'wyi': 'Tiếng Woiwurrung',
    'wym': 'Tiếng Wymysorys',
    'xaa': 'Tiếng Ả Rập Andalusia',
    'xag': 'Tiếng Aghwan',
    'xal': 'Tiếng Kalmyk',
    'xan': 'Tiếng Xamtanga',
    'xas': 'Tiếng Kamassia',
    'xbc': 'Tiếng Bactria',
    'xbo': 'Tiếng Bulgar',
    'xcc': 'Tiếng Camuni',
    'xcl': 'Tiếng Armenia cổ',
    'xco': 'Tiếng Khwarezm',
    'xcv': 'Tiếng Chuvan',
    'xdq': 'Tiếng Kaitag',
    'xfa': 'Tiếng Falisci',
    'xgn-mgl': 'Tiếng Mongghul',
    'xgn-mgr': 'Tiếng Mangghuer',
    'xh': 'Tiếng Xhosa',
    'xhm': 'Tiếng Khmer trung đại',
    'xis': 'Tiếng Kisan',
    'xka': 'Tiếng Kalkot',
    'xkf': 'Tiếng Khengkha',
    'xks': 'Tiếng Kumbewaha',
    'xkz': 'Tiếng Kurtokha',
    'xla': 'Tiếng Kamula',
    'xle': 'Tiếng Lemnos',
    'xlp': 'Tiếng Leponti',
    'xme-ker': 'Tiếng Kerman',
    'xmf': 'Tiếng Mingrelia',
    'xnb': 'Tiếng Kanakanavu',
    'xng': 'Tiếng Mông Cổ trung đại',
    'xpc': 'Tiếng Pecheneg',
    'xpg': 'Tiếng Phrygia',
    'xpm': 'Tiếng Pumpokol',
    'xpr': 'Tiếng Parthia',
    'xqa': 'Tiếng Karakhanid',
    'xrn': 'Tiếng Arin',
    'xrr': 'Tiếng Raetia',
    'xsa': 'Tiếng Saba',
    'xsb': 'Tiếng Sambali',
    'xsr': 'Tiếng Sherpa',
    'xsy': 'Tiếng Saisiyat',
    'xto': 'Tiếng Tochari A',
    'xua': 'Tiếng Kurumba Alu',
    'xub': 'Tiếng Kurumba Betta',
    'xug': 'Tiếng Kunigami',
    'xuj': 'Tiếng Kurumba Jennu',
    'xum': 'Tiếng Umbria',
    'xve': 'Tiếng Veneti',
    'xvo': 'Tiếng Volsci',
    'xwo': 'Tiếng Oirat',
    'yah': 'Tiếng Yazghulom',
    'yai': 'Tiếng Yaghnob',
    'yak': 'Tiếng Yakima',
    'yao': 'Tiếng Yao',
    'ybe': 'Tiếng Tây Yugur',
    'ybh': 'Tiếng Yakkha',
    'ycr': 'Tiếng Creole Nghi Lan',
    'ydg': 'Tiếng Yidgha',
    'yea': 'Tiếng Ravula',
    'yi': 'Tiếng Yiddish',
    'yin': 'Tiếng Riang Lai',
    'yka': 'Tiếng Yakan',
    'ykg': 'Tiếng Bắc Yukaghir',
    'ykh': 'Tiếng Mông Cổ Khamnigan',
    'yle': 'Tiếng Yele',
    'yli': 'Tiếng Yali Angguruk',
    'ymm': 'Tiếng Maay',
    'yno': 'Tiếng Yong',
    'yo': 'Tiếng Yoruba',
    'yog': 'Tiếng Yogad',
    'yoi': 'Tiếng Yonaguni',
    'yol': 'Tiếng Yola',
    'yon': 'Tiếng Yongkom',
    'yox': 'Tiếng Yoron',
    'yoy': 'Tiếng Yoy',
    'yrk': 'Tiếng Nenets lãnh nguyên',
    'yrl': 'Tiếng Nheengatu',
    'yro': 'Tiếng Ỹaroamë',
    'ysr': 'Tiếng Sirenik',
    'yua': 'Tiếng Maya Yucatán',
    'yue': 'Tiếng Quảng Đông',
    'yug': 'Tiếng Yugh',
    'yux': 'Tiếng Nam Yukaghir',
    'yuy': 'Tiếng Đông Yugur',
    'za': 'Tiếng Tráng',
    'zab': 'Tiếng Zapotec San Juan Guelavía',
    'zag': 'Tiếng Zaghawa',
    'zau': 'Tiếng Zangskar',
    'zay': 'Tiếng Zayse-Zergulla',
    'zea': 'Tiếng Zeeland',
    'zen': 'Tiếng Zenaga',
    'zgh': 'Tiếng Tamazight Maroc chuẩn',
    'zgr': 'Tiếng Magori',
    'zh': 'Tiếng Trung Quốc',
    'zhb': 'Tiếng Trát Bá',
    'zhn': 'Tiếng Tráng Nông',
    'zhx-taz': 'Tiếng Taz',
    'zhx-twa': 'Tiếng Đường Uông',
    'zkb': 'Tiếng Koibal',
    'zkd': 'Tiếng Kadu',
    'zkh': 'Tiếng Turk Khorezm',
    'zkn': 'Tiếng Kanan',
    'zko': 'Tiếng Kott',
    'zle-ort': 'Tiếng Ruthenia cổ',
    'zls-chs': 'Tiếng Slav Giáo hội',
    'zlw-ocs': 'Tiếng Séc cổ',
    'zlw-opl': 'Tiếng Ba Lan cổ',
    'zlw-osk': 'Tiếng Slovak cổ',
    'zlw-slv': 'Tiếng Slovincia',
    'zng': 'Tiếng Mảng',
    'zns': 'Tiếng Mangas',
    'zpw': 'Tiếng Zapotec Zaniza',
    'zrn': 'Tiếng Zirenkel',
    'zu': 'Tiếng Zulu',
    'zum': 'Tiếng Kumzar',
    'zwa': 'Tiếng Zay',
    'zyg': 'Tiếng Tráng Đức Tĩnh',
    'zza': 'Tiếng Zaza',
    'zzj': 'Tiếng Tráng Tả Giang',
    'unknown': 'Không xác định'
};
